# Archivos/directorios que deben analizarse (código fuente de tu app)
sonar.sources=app,config,database,routes,resources

# Directorios y archivos excluidos del análisis
sonar.exclusions=vendor/**,node_modules/**,public/storage/**,storage/**,bootstrap/cache/**,config/**