sonar.projectKey=AlejandroMoyaRuiz_Shop_Online
sonar.organization=alejandromoyaruiz

# EXCLUSIONES OBLIGATORIAS
sonar.exclusions=vendor/**, node_modules/**, public/build/**, storage/**, bootstrap/cache/**, lang/**

# Tipado de lenguaje
sonar.php.version=8.2